CREATE TABLE Movie (id INT PRIMARY KEY, title VARCHAR(100), year INT, rating VARCHAR(10), company VARCHAR(50), CHECK(id <= MaxMovieID(id))) ENGINE = INNODB;
CREATE TABLE Actor (id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), sex VARCHAR(6), dob DATE NOT NULL, dod DATE, CHECK(id <= MaxPersonID(id))) ENGINE = INNODB;
CREATE TABLE Director (id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), dob DATE NOT NULL, dod DATE, CHECK(id <= MaxPersonID(id))) ENGINE = INNODB;
CREATE TABLE MovieGenre (mid INT, genre VARCHAR(20)) ENGINE = INNODB;
CREATE TABLE MovieDirector (mid INT, did INT) ENGINE = INNODB;
CREATE TABLE MovieActor (mid INT, aid INT, role VARCHAR(50)) ENGINE = INNODB;
CREATE TABLE Review (name VARCHAR(20), time TIMESTAMP, mid INT, rating INT, comment VARCHAR(500)) ENGINE = INNODB;
CREATE TABLE MaxPersonID (id INT) ENGINE = INNODB;
CREATE TABLE MaxMovieID (id INT) ENGINE = INNODB;

ALTER TABLE MovieGenre
ADD FOREIGN KEY (mid) REFERENCES Movie(id);

ALTER TABLE MovieDirector
ADD FOREIGN KEY(mid) REFERENCES Movie(id);

ALTER TABLE MovieDirector
ADD FOREIGN KEY(did) REFERENCES Director(id);

ALTER TABLE MovieActor
ADD FOREIGN KEY(mid) REFERENCES Movie(id);

ALTER TABLE MovieActor
ADD FOREIGN KEY(aid) REFERENCES Actor(id);

ALTER TABLE Review
ADD FOREIGN KEY(mid) REFERENCES Movie(id);

